services:
  - type: static
    name: echo-app
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    redirects:
      - source: "/*"
        destination: "/index.html"
        type: "rewrite"
    envVars:
      - key: VITE_API_BASE
        value: https://echo-api-rvmq.onrender.com
